name: Production

on:
  workflow_run:
    workflows: ["Staging"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
