name: Staging

on:
  workflow_run:
    workflows: ["Development"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Approve deployment
      run: echo "Please manually approve the deployment in the 'staging' environment"
